# Generated by Django 4.2.30 on 2026-05-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Comment', models.CharField(max_length=512)),
                ('Links', models.CharField(max_length=512)),
                ('Deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('NE', 'New'), ('De', 'Demo'), ('FX', 'Fixing'), ('RE', 'Recording'), ('TR', 'Trackout'), ('MX', 'Mixing'), ('FI', 'Finished')], default='NE', max_length=50)),
                ('Price', models.IntegerField(default=18000)),
                ('Prep', models.IntegerField(default=0)),
                ('Postp', models.IntegerField(default=0)),
                ('Delta', models.IntegerField(default=0)),
                ('Start_date', models.DateField()),
                ('Post_date', models.DateField()),
                ('Deadline', models.DateField()),
                ('Comment', models.CharField(max_length=512)),
                ('Artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minicrm.artist')),
            ],
        ),
    ]
