# Generated by Django 4.2.30 on 2026-05-12 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minicrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
