# Generated by Django 4.2.30 on 2026-05-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicrm', '0002_artist_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Postp_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Prep_done',
            field=models.BooleanField(default=False),
        ),
    ]
