# Generated by Django 4.2.30 on 2026-05-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicrm', '0003_project_postp_done_project_prep_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('NEW', 'New'), ('DEM', 'Demo'), ('FIX', 'Fixing'), ('REC', 'Recording'), ('TRO', 'Trackout'), ('MIX', 'Mixing'), ('FIN', 'Finished')], default='NE', max_length=50),
        ),
    ]
