# Generated by Django 4.2.30 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minicrm', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('New', 'New'), ('Demo', 'Demo'), ('Fixing', 'Fixing'), ('Recording', 'Recording'), ('Trackout', 'Trackout'), ('Ming', 'Mixing'), ('Finished', 'Finished')], default='NE', max_length=50),
        ),
    ]
